Repositories as traits
Poietic/poietic pull request #9
Opened 2024-03-28 21:09 UTC by LucasHazardous

All tests pass except for "composition_fetching_by_page" but it didn't pass before my changes anyway.

2024-03-29 15:18 UTC, Dudu7352 approved these changes

2024-03-30 14:21 UTC, lechos22 commented
Didn't notice that before, but it seems to be my fault, so I'll fix it now

2024-03-30 14:46 UTC, lechos22 requested changes
Why not add Future to imports to increase readability?

2024-03-30 14:46 UTC, lechos22 commented on src/database/data_access/composition.rs
> +    ) -> impl std::future::Future<Output = Result<Composition, DatabaseError>> + Send;
Why not add Future to imports to increase readability?

2024-03-30 14:48 UTC, lechos22 commented
Other than that, everything looks good

2024-03-31 19:52 UTC, LucasHazardous commented
Changes applied. Thanks for fixing tests.

2024-03-31 19:52 UTC, merged